# Generated by Django 6.1.1 on 2026-09-16 11:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(help_text='Unique company code (e.g. COMP101)', max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=120)),
                ('hr_name', models.CharField(max_length=100)),
                ('hr_email', models.EmailField(max_length=254)),
                ('job_role', models.CharField(max_length=100)),
                ('package', models.DecimalField(decimal_places=2, help_text='Package in LPA (Lakhs Per Annum)', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01, message='Package must be greater than 0')])),
                ('location', models.CharField(max_length=100)),
                ('required_skills', models.TextField(blank=True)),
                ('drive_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-drive_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Unique roll number or student ID (e.g. STU202601)', max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=50)),
                ('year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=4)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0, message='CGPA cannot be less than 0.00'), django.core.validators.MaxValueValidator(10.0, message='CGPA cannot exceed 10.00')])),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills (e.g. Python, Django, React)')),
                ('placement_status', models.CharField(choices=[('Placed', 'Placed'), ('Not Placed', 'Not Placed')], default='Not Placed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_id', models.CharField(help_text='Unique placement record ID (e.g. PLC001)', max_length=20, unique=True)),
                ('job_role', models.CharField(max_length=100)),
                ('package', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01, message='Package must be greater than 0')])),
                ('placement_date', models.DateField()),
                ('status', models.CharField(choices=[('Selected', 'Selected'), ('Offered', 'Offered'), ('Joined', 'Joined'), ('Pending', 'Pending')], default='Selected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='placements_app.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='placements_app.student')),
            ],
            options={
                'ordering': ['-placement_date', '-created_at'],
            },
        ),
    ]
